### ISSUE TITLE
URL bar and selection menus are transparents

### ISSUE THREAD

**Issue by Blackrucat** [Blu3Jive001/Firefox-CSS#2]
**URL bar and selection menus are transparent!**
![image](https://user-images.githubusercontent.com/56588184/125859432-2ac569fa-7f40-4c06-8582-d4c286e6ec5a.png)

**Are they supposed to be like that?**
If they are supposed to be like that, they should be at least semi-transparent for a better reading.

**Comment by Blu3Jive001** [comment]
Firefox updated, and this code didn't. Sorry
